using System;
using System.Collections.Generic;
using System.Text;

namespace ProjectEuler
{
    class Problem_0002 : IProblem<long>
    {
        private const int LIMIT = 4000000;

        public string Question
        {
            get => "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
                "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
        }

        public long Answer()
        {
            return SumOfvenFibonacciNumbers(LIMIT);
        }

        private static long SumOfvenFibonacciNumbers(int limit)
        {
            var first = 1;
            var second = 2;
            var sum = second;
            do
            {
                var secondCopy = second;
                second = first + second;
                first = secondCopy;
                if (second % 2 == 0)
                {
                    sum += second;
                }
            } while (second <= limit);
            return sum;
        }
    }
}
